cart/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.view_cart,name='view_cart'),
    path('add/<int:product_id>',views.add_cart,name='add_cart'),
    path('remove_all/<int:product_id>',views.remove_all_cart,name='remove_all_cart'),
    path('decrease_quantity/<int:product_id>',views.decrease_quantity,name='decrease_quantity'),
]

djangoEcommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('store.urls')),
    path("accounts/", include('accounts.urls')),
    path('cart/',include('cart.urls')),
    path('order/', include('order.urls')),
    path('management/', include('management.urls')),
]

# Serve file media durante lo sviluppo
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.manager_vision, name='manager_home'),
    path('list_product',views.ManagerProductView.as_view(), name='manage_products'),
    path('product/<int:product_id>/',views.manage_product, name='product_edit'),
    path('list_categories/',views.m_categories_list, name='manage_categories'),
    path('list_users/',views.m_users,name='manage_users'),
    path('list_orders/',views.ManagerOrderView.as_view(),name='manage_orders'),
    path('order_detail/<int:order_id>',views.order_detail,name='order_detail'),
    path('add_product/',views.create_product,name='create_product'),
    path('delete/<int:product_id>',views.delete_product,name='delete_product'),
]

cart/models.py
from django.db import models
from django.db.models import CASCADE
from store.models import Product
from accounts.models import CustomUser


# Create your models here.

class CartItem(models.Model):
    customer=models.ForeignKey(CustomUser, on_delete=CASCADE)
    product=models.ForeignKey(Product,on_delete=CASCADE)
    quantity=models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} - {self.product.name} - {self.customer.username}"

management/models.py
from django.db import models

# Create your models here.

order/models.py
from django.db import models
from django.db.models import CASCADE
from store.models import Product
from accounts.models import CustomUser
import datetime
from django_countries.fields import CountryField

SHIPMENT_STATUS=[
    ("PENDING","PENDING"),
    ("IN_TRANSIT","IN TRANSIT"),
    ("DELIVERED","DELIVERED"),
    ("LOST","LOST"),
]

# Create your models here.

#Invece di mettere una foreignkey su UserAddress lo copiamo. Questo perché se poi l'indirizzo utilizzato venisse copiato
#lo storico ordini muterebbe
class Order(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete=CASCADE)
    total_price=models.DecimalField(max_digits=10, decimal_places=2)
    datetime = models.DateTimeField(default=datetime.datetime.today)
    status = models.CharField(choices=SHIPMENT_STATUS, default="PENDING")
    shipment_first_name = models.CharField(max_length=100)
    shipment_last_name = models.CharField(max_length=100)
    shipment_city = models.CharField(max_length=100)
    shipment_country = CountryField()
    shipment_postal_code = models.CharField(max_length=10)
    shipment_street_address = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.user} - {self.total_price} - {self.shipment_city}"

    @property
    def address_str(self):
        return f"{self.full_name} - {self.shipment_city} - {self.shipment_country} - {self.shipment_postal_code} - {self.shipment_street_address}"

    @property
    def full_name(self):
        return f"{self.shipment_first_name} {self.shipment_last_name}"
    @property
    def user(self):
        return self.customer.username


class OrderItem(models.Model):
    order=models.ForeignKey(Order, related_name='items',on_delete=CASCADE)
    product = models.ForeignKey(Product,on_delete=models.SET_NULL,null=True,blank=True)
    product_name = models.CharField(max_length=100)
    product_image = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=8, decimal_places=2)

    def __str__(self):
        return f"{self.product_name} - {self.quantity} - {self.order.customer.username}"
    def subtotal(self):
        return self.price * self.quantity

store/models.py
from django.db import models
from django.db.models import CASCADE
import datetime
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from cloudinary.models import CloudinaryField

# Create your models here.

#The product's categories
class Category(models.Model):
    name=models.CharField(max_length=20)
    def __str__(self):
        return self.name

#The products available in the store
class Product(models.Model):
    category=models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    name=models.CharField(max_length=100)
    price=models.DecimalField(default=0,decimal_places=2,max_digits=6,blank=False,null=False)
    front_image=CloudinaryField('image',folder="uploads/product",null=False,blank=False)
    description=models.CharField(max_length=500, default="", blank=True, null=True)
    quantity=models.PositiveIntegerField(default=0)
    is_active=models.BooleanField(default=True)
    discount=models.DecimalField(default=0,decimal_places=2,max_digits=6,blank=False,null=False)
    def __str__(self):
        return self.name
    @property
    def discounted_price(self):
        if 0 < self.discount < self.price:
            return self.price - self.discount
        return self.price
    @property
    def is_discounted(self):
        return self.discount > 0
    @property
    def discount_percent(self):
        if 0 < self.discount < self.price:
            percent = (self.discount / self.price) * 100
            return round(percent)
        return 0

    def increase_quantity(self,amount):
        self.quantity += amount

    def decrease_quantity(self,amount=1):
        if self.quantity >= amount:
            self.quantity -= amount
            if self.quantity == 0:
                self.is_active = False
            self.save()

management/views.py
from logging import raiseExceptions
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import permission_required, login_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.decorators import user_passes_test
from django_countries import countries
from order.models import Order, OrderItem
from .decorators import is_manager
from store.models import Product, Category
from accounts.models import CustomUser
from django.views.generic import ListView, TemplateView
from django.contrib import messages
from django.db.models.functions import Concat
from django.db.models import Value
from store.forms import ProductForm
from django.db.models import Q
from django.contrib.auth.models import Group
# Create your views here.


@login_required(login_url='login')
@user_passes_test(is_manager)
def manager_vision(request):
    return render(request, 'management/manager_vision.html')

@permission_required('store.add_product', raise_exception=True)
@permission_required('store.change_product', raise_exception=True)
@permission_required('store.delete_product', raise_exception=True)
def manage_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('manage_products')
        else:
            messages.error(request, "Error on form validation")
    else:
        form = ProductForm(instance=product)
    categories = Category.objects.all()  # Se usi ancora la lista nel template
    return render(request, "management/product_edit.html", {
        'form': form,
        'product': product,
        'categories': categories
    })
@permission_required('store.change_category', raise_exception=True)
@permission_required('store.add_category', raise_exception=True)
@permission_required('store.delete_category', raise_exception=True)
def m_categories_list(request):
    if request.method=="POST":
        action=request.POST.get('action')
        name=request.POST.get('name')
        category_id=request.POST.get('category_id')

        if action=="add":
            if name:
                Category.objects.create(name=name)
                messages.success(request,'Category added')
        elif action=="update":
            if category_id:
                Category.objects.filter(id=category_id).update(name=name)
                messages.success(request,'Category changed')
        elif action=="delete":
            if category_id:
                no_categorized = Product.objects.filter(category_id=category_id).count()
                Category.objects.filter(id=category_id).delete()
                if no_categorized==0:
                    messages.success(request,'Category deleted. No products changed')
                elif no_categorized==1:
                    messages.success(request,f"Category deleted. Now {no_categorized} product have no category")
                else:
                    messages.success(request, f"Category deleted. Now {no_categorized} products have no category")
        return redirect('manage_categories')
    else:
        categories = Category.objects.all()
        return render(request,'management/manage_categories.html',{'categories':categories})

@permission_required('accounts.view_customuser', raise_exception=True)
@permission_required('accounts.change_customuser', raise_exception=True)
@user_passes_test(is_manager)
def m_users(request):
    if request.method=="POST":
        user_id=request.POST.get('user_id')
        user=CustomUser.objects.get(id=user_id)
        action=request.POST.get('action')
        if request.user==user:
            messages.error(request,"You can't change your own role")
            return redirect('manage_users')

        if action=="make_manager":
            group = Group.objects.get(name='Manager')
            user.groups.clear()
            user.groups.add(group)
            messages.success(request, f"{user.username} è ora Manager")
        if action=="make_customer":
            group = Group.objects.get(name='Customer')
            user.groups.clear()
            user.groups.add(group)
            messages.success(request, f"{user.username} è ora Customer")
        return redirect('manage_users')
    else:
        users = CustomUser.objects.filter()
        context_name = request.GET.get('user_search')
        if context_name:
            users = CustomUser.objects.annotate(
                full_name_db=Concat('first_name', Value(' '), 'last_name')
            ).filter(
                Q(username__icontains=context_name) |
                Q(first_name__icontains=context_name) |
                Q(last_name__icontains=context_name) |
                Q(full_name_db__icontains=context_name)
            )
        return render(request,'management/manage_users.html',{'users':users,'searched':context_name})

class ManagerOrderView(PermissionRequiredMixin, ListView):
    model=Order
    template_name='management/manage_orders.html'
    context_object_name='orders'
    permission_required=['order.view_order',
                         'order.view_orderitem',
                         'order.change_order']

    def get_queryset(self):
        queryset = Order.objects.all()
        user_context=self.request.GET.get('user')
        product_name=self.request.GET.get('product')
        category_id=self.request.GET.get('category')
        country_code=self.request.GET.get('country')
        city=self.request.GET.get('city')
        status=self.request.GET.get('status')

        if product_name:
            queryset=queryset.filter(items__product__name__icontains=product_name)
        if status:
            queryset=queryset.filter(status=status)
        if category_id:
            queryset=queryset.filter(items__product__category_id=category_id)
        if country_code:
            queryset = queryset.filter(shipment_country=country_code)
        if city:
            queryset = queryset.filter(Q(**{ 'shipment_city__icontains': city }))
        if user_context:
            queryset = queryset.annotate(
                full_name_db=Concat('customer__first_name', Value(' '), 'customer__last_name'),
            ).filter(
                Q(customer__username__icontains=user_context) |
                Q(customer__first_name__icontains=user_context) |
                Q(customer__last_name__icontains=user_context) |
                Q(full_name_db__icontains=user_context)
            )
        return queryset

    def get_context_data(
            self, *, object_list=..., **kwargs
    ):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        used_codes = Order.objects.values_list('shipment_country', flat=True).distinct()
        used_countries = [(code, countries.name(code)) for code in used_codes if code]
        context['countries'] = list(used_countries)
        context['status_choices'] = order_status_choices=Order._meta.get_field('status').choices
        return context

@permission_required("order.view_order")
@permission_required("order.change_order")
def order_detail(request,order_id):
    order = Order.objects.get(id=order_id)
    order_status_choices=Order._meta.get_field('status').choices

    if request.method=="POST":
        new_status=request.POST.get('status')
        if new_status in dict(order_status_choices):
            order.status=new_status
            order.save()
            messages.success(request,f"Order status changed to {new_status}")
        else:
            messages.error(request,f"Invalid order status")
        return redirect('order_detail',order_id=order_id)
    else:
        return render(request,'management/order_detail.html',{'order':order,'status_choices':order_status_choices})

class ManagerProductView(PermissionRequiredMixin, ListView):
    model = Product  # indica il modello da cui prendere i dati
    template_name = 'management/manage_products.html'  # il tuo template personalizzato
    context_object_name = 'products'
    permission_required = ['store.add_product',
                           'store.delete_product']

    def get_queryset(self):
        queryset = Product.objects.filter()
        category_id=self.request.GET.get('category')
        name=self.request.GET.get('name')
        active=self.request.GET.get('active')
        if active:
            if active=='active':
                queryset=queryset.filter(is_active=True)
            else:
                queryset=queryset.filter(is_active=False)
        if category_id:
            queryset = queryset.filter(category_id=category_id)
        if name:
            queryset = queryset.filter(name__icontains=name)
        return queryset

    def get_context_data(
        self, *, object_list = ..., **kwargs
    ):
        context=super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context
@permission_required('store.add_product',raise_exception=True)
def create_product(request):
    if request.method=="POST":
        form=ProductForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('manage_products')
    else:
        form=ProductForm()
    return render(request,'management/create_product.html',{'form':form})

@permission_required("store.delete_product",raise_exception=True)
def delete_product(request,product_id):
    product = Product.objects.get(id=product_id)
    order_count = OrderItem.objects.filter(product=product).count()

    if request.method == "POST":
        product.delete()
        messages.success(request, "Product deleted with success")
        return redirect('manage_products')

    return render(request, 'management/delete_item.html', {
        'product': product,

management/templates/management/create_product.html
{% extends 'management/manager_vision_base.html' %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <h2 class="mb-4 mt-4">Add new Product</h2>

                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">{{ field.label }}: {{ error }}</div>
                    {% endfor %}
                {% endfor %}
                <div class="card shadow-sm">
                    <div class="card-body p-4">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_name" class="form-label"><strong>Product Name</strong></label>
                                {{ form.name|add_class:"form-control" }}
                            </div>
                            <div class="mb-3">
                                <label for="id_category" class="form-label"><strong>Category</strong></label>
                                {{ form.category|add_class:"form-select" }}
                            </div>
                            <div class="mb-3">
                                <label for="id_price" class="form-label"><strong>Price (€)</strong></label>
                                {{ form.price|add_class:"form-control" }}
                            </div>
                            <div class="mb-3">
                                <label for="id_quantity" class="form-label"><strong>Quantity</strong></label>
                                {{ form.quantity|add_class:"form-control" }}
                            </div>
                            <div class="mb-3">
                                <label for="id_discount" class="form-label"><strong>Discount (€)</strong></label>
                                {{ form.discount|add_class:"form-control" }}
                            </div>
                            <div class="mb-3">
                                <label for="id_description" class="form-label"><strong>Description</strong></label>
                                {{ form.description|add_class:"form-control" }}
                            </div>
                            <div class="mb-3">
                                <label for="id_front_image" class="form-label"><strong>Product Image</strong></label>
                                <div id="image-preview"
                                     class="position-relative justify-content-start"
                                     style="display: none;">
                                    <div class="position-relative d-inline-block">
                                        <button type="button"
                                                id="cancel-image-btn"
                                                aria-label="Cancel"
                                                class="btn btn-sm btn-danger position-absolute top-0 end-0 translate-middle"
                                                style="z-index: 2; padding: 0.25rem 0.5rem;">
                                            &times;
                                        </button>
                                        <img id="preview-img"
                                             class="img-thumbnail rounded border"
                                             style="max-width: 150px; height: auto;"
                                             alt="Preview image">
                                    </div>
                                </div>
                                {{ form.front_image|add_class:"form-control mt-2"}}
                            </div>
                            <div class="mb-3 form-check">
                                {{ form.is_active }}
                                <label class="form-check-label" for="id_is_active"><strong>Is active</strong></label>
                            </div>
                            <div class="d-flex justify-content-between mt-4">
                                <a href="{% url 'manage_products' %}" class="btn btn-outline-secondary">Cancel</a>
                                <button type="submit" class="btn btn-success">Create Product</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <script src="{% static 'js/create_product.js' %}"></script>
{% endblock %}

management/templates/management/delete_item.html
{% extends 'management/manager_vision_base.html' %}
{% block content %}
<div class="container py-5 text-dark" style="max-width: 800px;">
    <h2 class="mb-4">Delete Product</h2>

    <div class="card shadow-sm mb-4">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="{{ product.front_image.url }}" alt="{{ product.name }}"
                     class="img-fluid rounded-start" style="object-fit: cover; height: 100%;">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">{{ product.description }}</p>
                    <p class="card-text"><strong>Category:</strong> {{ product.category }}</p>
                    <p class="card-text"><strong>Price:</strong> €{{ product.price }}</p>
                    <p class="card-text"><strong>Quantity:</strong> {{ product.quantity }}</p>
                    <p class="card-text"><strong>Status:</strong>
                        {% if product.is_active %}
                            <span class="badge bg-success">Active</span>
                        {% else %}
                            <span class="badge bg-warning text-dark">Disabled</span>
                        {% endif %}
                    </p>
                    <p class="card-text">
                        <strong>Present in:</strong>
                        <span class="text-danger fw-bold">{{ order_count }}</span> order{{ order_count|pluralize }}
                    </p>
                </div>
            </div>
        </div>
    </div>
    <form method="post" onsubmit="return confirmDelete();">
        {% csrf_token %}
        <div class="text-end">
            <a href="{% url 'manage_products' %}" class="btn btn-outline-secondary">Cancel</a>
            <button type="submit" class="btn btn-danger">Delete Product</button>
        </div>
    </form>
</div>
<script>
    function confirmDelete() {
        return confirm("Are you sure you want to delete this product?");
    }
</script>
{% endblock %}

management/templates/management/manage_categories.html
{% extends "management/manager_vision_base.html" %}
{% block content %}

    <div class="container py-4" style="max-width: 900px;width: 100%">
        <h2 class="mb-4">Manage Categories</h2>
        <div class="list-group mb-4">
            {% for category in categories %}
                <div class="list-group-item d-flex align-items-center justify-content-between">
                    <form method="post" class="d-flex align-items-center gap-2 w-100" style="padding-right: 5px">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="update">
                        <input type="hidden" name="category_id" value="{{ category.id }}">
                        <input type="text" name="name" value="{{ category.name }}" class="form-control" required>
                        <button type="submit" class="btn btn-sm btn-outline-primary">Salva</button>
                    </form>

                    <form method="post">
                        {% csrf_token %}
                        <input type="hidden" name="action" value="delete">
                        <input type="hidden" name="category_id" value="{{ category.id }}">
                        <button type="submit" class="btn btn-sm btn-outline-danger">&times;</button>
                    </form>
                </div>
            {% empty %}
                <p class="text-muted">No categories created</p>
            {% endfor %}
        </div>
        <div class="text-center mb-3">
            <button class="btn btn-success" data-bs-toggle="collapse" data-bs-target="#addCategoryForm">
                + Add category
            </button>
        </div>
        <div class="collapse" id="addCategoryForm">
            <div class="card card-body shadow-sm" style="max-width: 500px; margin: auto;">
                <form method="post">
                    {% csrf_token %}
                    <input type="hidden" name="action" value="add">
                    <input type="text" class="form-control mb-2" name="name" placeholder="New category name" required>
                    <div class="text-center ">
                        <button type="submit" class="btn btn-primary">Create</button>
                    </div>
                </form>
            </div>
        </div>

    </div>

{% endblock %}

management/templates/management/manage_orders.html
{% extends 'management/manager_vision_base.html' %}
{% block content %}
    <div class="container-fluid mt-4">
        <div class="row">
            <div class="col-md-3 text-black">
                <div class="position-sticky" style="top: 100px;">
                    <form method="get" class="bg-light p-3 rounded shadow-sm">
                        <h5 class="mb-3">Filter orders</h5>
                        <div class="mb-3">
                            <label for="user_search" class="form-label">User (username or full name)</label>
                            <input type="text" name="user" class="form-control" id="user_search" value="{{ request.GET.user }}">
                        </div>
                        <div class="mb-3">
                            <label for="product_search" class="form-label">Product name</label>
                            <input type="text" name="product" class="form-control" id="product_search" value="{{ request.GET.product }}">
                        </div>

                        <div class="mb-3">
                            <label for="status" class="form-label">Shipment status</label>
                            <select name="status" class="form-select">
                                <option value="">All</option>
                                {% for key,label in status_choices %}
                                    <option value="{{ key }}" {% if request.GET.status == key %} selected {% endif %}>{{label}}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="mb-3">
                            <label for="category" class="form-label">Category</label>
                            <select name="category" class="form-select">
                                <option value="">All</option>
                                {% for cat in categories %}
                                    <option value="{{ cat.id }}" {% if request.GET.category == cat.id|stringformat:"s" %}selected{% endif %}>{{ cat.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="country" class="form-label">Country</label>
                            <select name="country" class="form-select">
                                <option value="">All</option>
                                {% for code, name in countries %}
                                    <option value="{{ code }}" {% if request.GET.country == code %}selected{% endif %}>{{ name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="mb-3">
                            <label for="city" class="form-label">City</label>
                            <input type="text" name="city" class="form-control" id="city" value="{{ request.GET.city }}">
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Filter</button>
                            <a type="button" class="btn btn-outline-danger" href="{% url 'manage_orders' %}">Reset filters</a>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-md-9" style="min-height: 100vh">
                <h2 class="fw-bold mb-4 mt-3 text-center">Manage Orders</h2>

                <div class="row row-gap-3">
                    {% for order in orders %}
                        <div class="col-12 col-sm-6 col-lg-4">
                            <a href="{% url 'order_detail' order.id %}" class="text-decoration-none text-dark">
                                <div class="card shadow-sm h-100">
                                    <div class="card-body">
                                        <h5 class="card-title fw-bold">#{{ order.id }}</h5>
                                        <p class="card-text">
                                            <label class="fw-bold">Customer:</label> {{ order.customer.first_name }} {{ order.customer.last_name }} | {{ order.customer.username }}<br>
                                            <label class="fw-bold">Shipment status:</label>
                                            <span class="badge
                                            {% if order.status == 'PENDING' %}bg-warning
                                            {% elif order.status == 'IN_TRANSIT' %}bg-secondary
                                            {% elif order.status == 'DELIVERED' %}bg-success
                                            {% elif order.status == 'LOST' %}bg-danger
                                            {% endif %}">
                                            {{ order.get_status_display }}
                                        </span><br>
                                            <label class="fw-bold">City-Country:</label> {{ order.shipment_city }} - {{ order.shipment_country }}<br>
                                            <label class="fw-bold">Total price:</label> {{ order.total_price }}€<br>
                                            <label class="fw-bold">Date:</label> {{ order.datetime|date:"d/m/Y" }}
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% empty %}
                        <p>No order found by the filters</p>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <!-- SCRIPT PER RESET -->
{% endblock %}